export const countries = [
  { title: 'United States', value: 'USA' },
  { title: 'Afghanistan', value: 'AFG' },
  { title: 'Albania', value: 'ALB' },
  { title: 'Algeria', value: 'DZA' },
  { title: 'Andorra', value: 'AND' },
  { title: 'Angola', value: 'AGO' },
  { title: 'Antigua and Barbuda', value: 'ATG' },
  { title: 'Argentina', value: 'ARG' },
  { title: 'Armenia', value: 'ARM' },
  { title: 'Australia', value: 'AUS' },
  { title: 'Austria', value: 'AUT' },
  { title: 'Azerbaijan', value: 'AZE' },
  { title: 'Bahamas', value: 'BHS' },
  { title: 'Bahrain', value: 'BHR' },
  { title: 'Bangladesh', value: 'BGD' },
  { title: 'Barbados', value: 'BRB' },
  { title: 'Belarus', value: 'BLR' },
  { title: 'Belgium', value: 'BEL' },
  { title: 'Belize', value: 'BLZ' },
  { title: 'Benin', value: 'BEN' },
  { title: 'Bhutan', value: 'BTN' },
  { title: 'Bolivia', value: 'BOL' },
  { title: 'Bosnia and Herzegovina', value: 'BIH' },
  { title: 'Botswana', value: 'BWA' },
  { title: 'Brazil', value: 'BRA' },
  { title: 'Brunei', value: 'BRN' },
  { title: 'Bulgaria', value: 'BGR' },
  { title: 'Burkina Faso', value: 'BFA' },
  { title: 'Burundi', value: 'BDI' },
  { title: 'Cabo Verde', value: 'CPV' },
  { title: 'Cambodia', value: 'KHM' },
  { title: 'Cameroon', value: 'CMR' },
  { title: 'Canada', value: 'CAN' },
  { title: 'Central African Republic', value: 'CAF' },
  { title: 'Chad', value: 'TCD' },
  { title: 'Chile', value: 'CHL' },
  { title: 'China', value: 'CHN' },
  { title: 'Colombia', value: 'COL' },
  { title: 'Comoros', value: 'COM' },
  { title: 'Congo, Democratic Republic of the', value: 'COD' },
  { title: 'Congo, Republic of the', value: 'COG' },
  { title: 'Costa Rica', value: 'CRI' },
  { title: 'Croatia', value: 'HRV' },
  { title: 'Cuba', value: 'CUB' },
  { title: 'Cyprus', value: 'CYP' },
  { title: 'Czech Republic', value: 'CZE' },
  { title: 'Denmark', value: 'DNK' },
  { title: 'Djibouti', value: 'DJI' },
  { title: 'Dominica', value: 'DMA' },
  { title: 'Dominican Republic', value: 'DOM' },
  { title: 'East Timor', value: 'TLS' },
  { title: 'Ecuador', value: 'ECU' },
  { title: 'Egypt', value: 'EGY' },
  { title: 'El Salvador', value: 'SLV' },
  { title: 'Equatorial Guinea', value: 'GNQ' },
  { title: 'Eritrea', value: 'ERI' },
  { title: 'Estonia', value: 'EST' },
  { title: 'Eswatini', value: 'SWZ' },
  { title: 'Ethiopia', value: 'ETH' },
  { title: 'Fiji', value: 'FJI' },
  { title: 'Finland', value: 'FIN' },
  { title: 'France', value: 'FRA' },
  { title: 'Gabon', value: 'GAB' },
  { title: 'Gambia', value: 'GMB' },
  { title: 'Georgia', value: 'GEO' },
  { title: 'Germany', value: 'DEU' },
  { title: 'Ghana', value: 'GHA' },
  { title: 'Greece', value: 'GRC' },
  { title: 'Grenada', value: 'GRD' },
  { title: 'Guatemala', value: 'GTM' },
  { title: 'Guinea', value: 'GIN' },
  { title: 'Guinea-Bissau', value: 'GNB' },
  { title: 'Guyana', value: 'GUY' },
  { title: 'Haiti', value: 'HTI' },
  { title: 'Honduras', value: 'HND' },
  { title: 'Hungary', value: 'HUN' },
  { title: 'Iceland', value: 'ISL' },
  { title: 'India', value: 'IND' },
  { title: 'Indonesia', value: 'IDN' },
  { title: 'Iran', value: 'IRN' },
  { title: 'Iraq', value: 'IRQ' },
  { title: 'Ireland', value: 'IRL' },
  { title: 'Israel', value: 'ISR' },
  { title: 'Italy', value: 'ITA' },
  { title: 'Jamaica', value: 'JAM' },
  { title: 'Japan', value: 'JPN' },
  { title: 'Jordan', value: 'JOR' },
  { title: 'Kazakhstan', value: 'KAZ' },
  { title: 'Kenya', value: 'KEN' },
  { title: 'Kiribati', value: 'KIR' },
  { title: 'Korea, North', value: 'PRK' },
  { title: 'Korea, South', value: 'KOR' },
  { title: 'Kosovo', value: 'XKX' },
  { title: 'Kuwait', value: 'KWT' },
  { title: 'Kyrgyzstan', value: 'KGZ' },
  { title: 'Laos', value: 'LAO' },
  { title: 'Latvia', value: 'LVA' },
  { title: 'Lebanon', value: 'LBN' },
  { title: 'Lesotho', value: 'LSO' },
  { title: 'Liberia', value: 'LBR' },
  { title: 'Libya', value: 'LBY' },
  { title: 'Liechtenstein', value: 'LIE' },
  { title: 'Lithuania', value: 'LTU' },
  { title: 'Luxembourg', value: 'LUX' },
  { title: 'Madagascar', value: 'MDG' },
  { title: 'Malawi', value: 'MWI' },
  { title: 'Malaysia', value: 'MYS' },
  { title: 'Maldives', value: 'MDV' },
  { title: 'Mali', value: 'MLI' },
  { title: 'Malta', value: 'MLT' },
  { title: 'Marshall Islands', value: 'MHL' },
  { title: 'Mauritania', value: 'MRT' },
  { title: 'Mauritius', value: 'MUS' },
  { title: 'Mexico', value: 'MEX' },
  { title: 'Micronesia', value: 'FSM' },
  { title: 'Moldova', value: 'MDA' },
  { title: 'Monaco', value: 'MCO' },
  { title: 'Mongolia', value: 'MNG' },
  { title: 'Montenegro', value: 'MNE' },
  { title: 'Morocco', value: 'MAR' },
  { title: 'Mozambique', value: 'MOZ' },
  { title: 'Myanmar (Burma)', value: 'MMR' },
  { title: 'Namibia', value: 'NAM' },
  { title: 'Nauru', value: 'NRU' },
  { title: 'Nepal', value: 'NPL' },
  { title: 'Netherlands', value: 'NLD' },
  { title: 'New Zealand', value: 'NZL' },
  { title: 'Nicaragua', value: 'NIC' },
  { title: 'Niger', value: 'NER' },
  { title: 'Nigeria', value: 'NGA' },
  { title: 'North Macedonia', value: 'MKD' },
  { title: 'Norway', value: 'NOR' },
  { title: 'Oman', value: 'OMN' },
  { title: 'Pakistan', value: 'PAK' },
  { title: 'Palau', value: 'PLW' },
  { title: 'Panama', value: 'PAN' },
  { title: 'Papua New Guinea', value: 'PNG' },
  { title: 'Paraguay', value: 'PRY' },
  { title: 'Peru', value: 'PER' },
  { title: 'Philippines', value: 'PHL' },
  { title: 'Poland', value: 'POL' },
  { title: 'Portugal', value: 'PRT' },
  { title: 'Qatar', value: 'QAT' },
  { title: 'Romania', value: 'ROU' },
  { title: 'Russia', value: 'RUS' },
  { title: 'Rwanda', value: 'RWA' },
  { title: 'Saint Kitts and Nevis', value: 'KNA' },
  { title: 'Saint Lucia', value: 'LCA' },
  { title: 'Saint Vincent and the Grenadines', value: 'VCT' },
  { title: 'Samoa', value: 'WSM' },
  { title: 'San Marino', value: 'SMR' },
  { title: 'Sao Tome and Principe', value: 'STP' },
  { title: 'Saudi Arabia', value: 'SAU' },
  { title: 'Senegal', value: 'SEN' },
  { title: 'Serbia', value: 'SRB' },
  { title: 'Seychelles', value: 'SYC' },
  { title: 'Sierra Leone', value: 'SLE' },
  { title: 'Singapore', value: 'SGP' },
  { title: 'Slovakia', value: 'SVK' },
  { title: 'Slovenia', value: 'SVN' },
  { title: 'Solomon Islands', value: 'SLB' },
  { title: 'Somalia', value: 'SOM' },
  { title: 'South Africa', value: 'ZAF' },
  { title: 'South Sudan', value: 'SSD' },
  { title: 'Spain', value: 'ESP' },
  { title: 'Sri Lanka', value: 'LKA' },
  { title: 'Sudan', value: 'SDN' },
  { title: 'Suriname', value: 'SUR' },
  { title: 'Sweden', value: 'SWE' },
  { title: 'Switzerland', value: 'CHE' },
  { title: 'Syria', value: 'SYR' },
  { title: 'Taiwan', value: 'TWN' },
  { title: 'Tajikistan', value: 'TJK' },
  { title: 'Tanzania', value: 'TZA' },
  { title: 'Thailand', value: 'THA' },
  { title: 'Togo', value: 'TGO' },
  { title: 'Tonga', value: 'TON' },
  { title: 'Trinidad and Tobago', value: 'TTO' },
  { title: 'Tunisia', value: 'TUN' },
  { title: 'Turkey', value: 'TUR' },
  { title: 'Turkmenistan', value: 'TKM' },
  { title: 'Tuvalu', value: 'TUV' },
  { title: 'Uganda', value: 'UGA' },
  { title: 'Ukraine', value: 'UKR' },
  { title: 'United Arab Emirates', value: 'ARE' },
  { title: 'United Kingdom', value: 'GBR' },
  { title: 'Uruguay', value: 'URY' },
  { title: 'Uzbekistan', value: 'UZB' },
  { title: 'Vanuatu', value: 'VUT' },
  { title: 'Vatican City', value: 'VAT' },
  { title: 'Venezuela', value: 'VEN' },
  { title: 'Vietnam', value: 'VNM' },
  { title: 'Yemen', value: 'YEM' },
  { title: 'Zambia', value: 'ZMB' },
  { title: 'Zimbabwe', value: 'ZWE' },
];
