name: Release

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v4
        with:
          # Ensure that git uses your token with admin access to the repo
          token: ${{ secrets.GH_ADMIN_TOKEN }}
      - name: Prepare repository
        run: git fetch --unshallow --tags
      - uses: actions/setup-node@v4
        with:
          node-version: 19
          registry-url: https://npm.pkg.github.com/
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn install --frozen-lockfile
          yarn build
          npx auto shipit
